package generator

const CppTemplate = `// Generated by github.com/IronsDu/protoc-gen-gayrpc
// Coding by github.com/liuhan907
// DO NOT EDIT!!!

#ifndef {{$.MacroName}}
#define {{$.MacroName}}

#include <string_view>
#include <string>
#include <unordered_map>
#include <memory>
#include <cstdint>
#include <future>
#include <chrono>

#include <google/protobuf/util/json_util.h>

#include <gayrpc/core/gayrpc_meta.pb.h>
#include "{{$.ModelFileName}}"

#include <gayrpc/core/GayRpcType.h>
#include <gayrpc/core/GayRpcError.h>
#include <gayrpc/core/GayRpcTypeHandler.h>
#include <gayrpc/core/GayRpcClient.h>
#include <gayrpc/core/GayRpcService.h>
#include <gayrpc/core/GayRpcReply.h>

{{range $i, $packageName := $.PackageNames}}namespace {{$packageName}} {
{{end}}
    using namespace gayrpc::core;
    using namespace google::protobuf::util;
    
    enum class {{$.Namespace}}_ServiceID:uint32_t
    {
        {{range $serviceIndex, $service := $.Services}}{{$service.Name}},
        {{end}}
    };

    {{range $serviceIndex, $service := $.Services}}
    enum class {{$service.MethodsEnumName}}:uint64_t
    {
        {{range $i, $method := $service.Methods}}{{$method.EnumName}} = {{$method.MethodID}},
        {{end}}
    };

    class {{$service.Name}}Client : public BaseClient
    {
    public:
        using PTR = std::shared_ptr<{{$service.Name}}Client>;
        using WeakPtr = std::weak_ptr<{{$service.Name}}Client>;

        {{range $i, $method := $service.Methods}}using {{$method.Name}}Handle = std::function<void(const {{$.ContainerNamespace}}{{$method.OutputType}}&, const gayrpc::core::RpcError&)>;
        {{end}}

    public:
        {{range $i, $method := $service.Methods}}void {{$method.MethodName}}(const {{$.ContainerNamespace}}{{$method.InputType}}& request,
            const {{$method.Name}}Handle& handle = nullptr)
        {
            call<{{$.ContainerNamespace}}{{$method.OutputType}}>(request, 
                static_cast<uint32_t>({{$.Namespace}}_ServiceID::{{$service.Name}}), 
                static_cast<uint64_t>({{$service.MethodsEnumName}}::{{$method.EnumName}}), 
                handle);
        }
        {{end}}
        {{range $i, $method := $service.Methods}}void {{$method.MethodName}}(const {{$.ContainerNamespace}}{{$method.InputType}}& request,
            const {{$method.Name}}Handle& handle,
            std::chrono::seconds timeout, 
            BaseClient::TIMEOUT_CALLBACK&& timeoutCallback)
        {
            call<{{$.ContainerNamespace}}{{$method.OutputType}}>(request, 
                static_cast<uint32_t>({{$.Namespace}}_ServiceID::{{$service.Name}}), 
                static_cast<uint64_t>({{$service.MethodsEnumName}}::{{$method.EnumName}}), 
                handle,
                timeout,
                std::move(timeoutCallback));
        }
        {{end}}

        {{range $i, $method := $service.Methods}}{{$.ContainerNamespace}}{{$method.OutputType}} Sync{{$method.MethodName}}(
            const {{$.ContainerNamespace}}{{$method.InputType}}& request,
            gayrpc::core::RpcError& error,
            std::chrono::seconds timeout)
        {
            auto errorPromise = std::make_shared<std::promise<gayrpc::core::RpcError>>();
            auto responsePointer = std::make_shared<{{$.ContainerNamespace}}{{$method.OutputType}}>();

            {{$method.MethodName}}(request, [responsePointer, errorPromise](const {{$.ContainerNamespace}}{{$method.OutputType}}& response,
                const gayrpc::core::RpcError& error) {
                *responsePointer = response;
                errorPromise->set_value(error);
            });

            auto errorFuture = errorPromise->get_future();
            if (errorFuture.wait_for(timeout) != std::future_status::ready)
            {
                throw std::runtime_error("timeout");
            }

            error = errorFuture.get();
            return *responsePointer;
        }
        {{end}}

    public:
        static PTR Create(const RpcTypeHandleManager::PTR& rpcHandlerManager,
            const UnaryServerInterceptor& inboundInterceptor,
            const UnaryServerInterceptor& outboundInterceptor)
        {
            class make_shared_enabler : public {{$service.Name}}Client
            {
            public:
                make_shared_enabler(const RpcTypeHandleManager::PTR& rpcHandlerManager,
                    const UnaryServerInterceptor& inboundInterceptor,
                    const UnaryServerInterceptor& outboundInterceptor)
                    : 
                    {{$service.Name}}Client(rpcHandlerManager, inboundInterceptor, outboundInterceptor) {}
            };

            auto client = PTR(new make_shared_enabler(rpcHandlerManager, inboundInterceptor, outboundInterceptor));
            client->installResponseStub(rpcHandlerManager, static_cast<uint32_t>({{$.Namespace}}_ServiceID::{{$service.Name}}));

            return client;
        }

        static  std::string GetServiceTypeName()
        {
            return "{{$.ContainerNamespace}}{{$service.Name}}";
        }

    private:
        using BaseClient::BaseClient;
    };

    class {{$service.Name}}Service : public BaseService
    {
    public:
        using PTR = std::shared_ptr<{{$service.Name}}Service>;
        using WeakPtr = std::weak_ptr<{{$service.Name}}Service>;

        {{range $i, $method := $service.Methods}}using {{$method.Name}}Reply = TemplateReply<{{$.ContainerNamespace}}{{$method.OutputType}}>;
        {{end}}

        using BaseService::BaseService;

        virtual ~{{$service.Name}}Service()
        {
        }

        virtual void onClose() {}

        static bool Install(const {{$service.Name}}Service::PTR& service);

        static  std::string GetServiceTypeName()
        {
            return "{{$.ContainerNamespace}}{{$service.Name}}";
        }
    private:
        {{range $i, $method := $service.Methods}}virtual void {{$method.MethodName}}(const {{$.ContainerNamespace}}{{$method.InputType}}& request, 
            const {{$.ContainerNamespace}}{{$service.Name}}Service::{{$method.Name}}Reply::PTR& replyObj,
            InterceptorContextType&&) = 0;
        {{end}}

    private:

        {{range $i, $method := $service.Methods}}static void {{$method.MethodName}}_stub(RpcMeta&& meta,
            const std::string_view& data,
            const {{$service.Name}}Service::PTR& service,
            const UnaryServerInterceptor& inboundInterceptor,
            const UnaryServerInterceptor& outboundInterceptor,
            InterceptorContextType&& context)
        {
            {{$.ContainerNamespace}}{{$method.InputType}} request;
            parseRequestWrapper(request, std::move(meta), data, inboundInterceptor, [service,
                outboundInterceptor = outboundInterceptor,
                &request](RpcMeta&& meta, const google::protobuf::Message& message, InterceptorContextType&& context) mutable {
                auto replyObject = std::make_shared<{{$method.Name}}Reply>(std::move(meta), std::move(outboundInterceptor));
                service->{{$method.MethodName}}(request, replyObject, std::move(context));
            }, std::move(context));
        }
        {{end}}
    };

    inline bool {{$service.Name}}Service::Install(const {{$service.Name}}Service::PTR& service)
    {
        auto rpcTypeHandleManager = service->getServiceContext().getTypeHandleManager();
        auto inboundInterceptor = service->getServiceContext().getInInterceptor();
        auto outboundInterceptor = service->getServiceContext().getOutInterceptor();

        using {{$service.Name}}ServiceRequestHandler = std::function<void(RpcMeta&&,
            const std::string_view& data,
            const {{$service.Name}}Service::PTR&,
            const UnaryServerInterceptor&,
            const UnaryServerInterceptor&,
            InterceptorContextType&& context)>;

        using {{$service.Name}}ServiceHandlerMapById = std::unordered_map<uint64_t, {{$service.Name}}ServiceRequestHandler>;
        using {{$service.Name}}ServiceHandlerMapByStr = std::unordered_map<std::string, {{$service.Name}}ServiceRequestHandler>;

        // TODO::static unordered map
        auto serviceHandlerMapById = std::make_shared<{{$service.Name}}ServiceHandlerMapById>();
        auto serviceHandlerMapByStr = std::make_shared<{{$service.Name}}ServiceHandlerMapByStr>();

        const std::string namespaceStr = "{{range $i, $packageName := $.PackageNames}}{{$packageName}}.{{end}}";

        {{range $i, $method := $service.Methods}}(*serviceHandlerMapById)[static_cast<uint64_t>({{$service.MethodsEnumName}}::{{$method.MethodName}})] = {{$service.Name}}Service::{{$method.MethodName}}_stub;
        {{end}}
        {{range $i, $method := $service.Methods}}(*serviceHandlerMapByStr)[namespaceStr+"{{$service.Name}}.{{$method.MethodName}}"] = {{$service.Name}}Service::{{$method.MethodName}}_stub;
        {{end}}

        auto requestStub = [service,
            serviceHandlerMapById,
            serviceHandlerMapByStr,
            inboundInterceptor,
            outboundInterceptor](RpcMeta&& meta, const std::string_view& data, InterceptorContextType&& context) {
            
            if (meta.type() != RpcMeta::REQUEST)
            {
                throw std::runtime_error("meta type not request, It is:" + std::to_string(meta.type()));
            }
            
            {{$service.Name}}ServiceRequestHandler handler;

            if (!meta.request_info().strmethod().empty())
            {
                auto it = serviceHandlerMapByStr->find(meta.request_info().strmethod());
                if (it == serviceHandlerMapByStr->end())
                {
                    throw std::runtime_error("not found handle, method:" + meta.request_info().strmethod());
                }
                handler = (*it).second;
            }
            else
            {
                auto it = serviceHandlerMapById->find(meta.request_info().intmethod());
                if (it == serviceHandlerMapById->end())
                {
                    throw std::runtime_error("not found handle, method:" + meta.request_info().intmethod());
                }
                handler = (*it).second;
            }

            handler(std::move(meta),
                data,
                service,
                inboundInterceptor,
                outboundInterceptor,
                std::move(context));
        };

        return rpcTypeHandleManager->registerTypeHandle(RpcMeta::REQUEST, requestStub, static_cast<uint32_t>({{$.Namespace}}_ServiceID::{{$service.Name}}));
    }
    {{end}}
{{range $i, $packageName := $.PackageNames}}}
{{end}}
#endif

`
